version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      fileapi-main-network:

  redis:
    image: "redis:latest"
    networks:
      fileapi-main-network:
        ipv4_address: 172.25.0.2

networks:
  fileapi-main-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
